### ISSUE TITLE
Error when building for Linux

### ISSUE THREAD

**Issue by citrusui** [loopline-systems/electron-builder#129]
Apparently `electron-builder` thinks my architecture is undefined.

Here's my config:
![screenshot from 2016-02-07 12 40 54](https://cloud.githubusercontent.com/assets/9056756/12873946/2d153086-cd98-11e5-8192-c20c37ac3780.png)

Here's the error:
![screenshot from 2016-02-07 12 35 55](https://cloud.githubusercontent.com/assets/9056756/12873949/3493b22e-cd98-11e5-8076-c302c02f140a.png)

This happens every time I run `electron-builder dist/win/someFancy-linux-x64 --platform=linux --config=config.json`. Any ideas on how to fix?

**Comment by stefanjudis** [comment]
Your config file doesn't look correct...

https://github.com/loopline-systems/electron-builder#parameters

**Comment by stefanjudis** [comment]
If you're going with a config file it should like that

```
{
  "linux" : {
    "arch" : 64,
    "target" : "deb",
    "version" : "x.x.x.x",
    "title" : "Loopline Systems",
    "comment" : "This is a comment",
    "executable" : "myExec",
    "maintainer": "Dummy Maintainer <dummy@maintainer.org>"
  }
}
```

**Comment by citrusui** [comment]
Okay, cool, I got my app to compile on Linux now.

However, it appears that the executable specified in `config.json` doesn't actually... compile. There's nothing in `/usr/bin`, just `/usr/share/applications/mypackage.desktop` (which links to `/usr/bin/mypackage`)

Screenie:
![screenshot from 2016-02-07 16 44 59](https://cloud.githubusercontent.com/assets/9056756/12875525/a4acbac0-cdba-11e5-8242-53659f4018fe.png)

Side note: `electron-packager` works fine when compiling my app, it just doesn't "package" the app (create a deb/rpm and create a .desktop file) for it.

**Comment by stefanjudis** [comment]
Hmm... Can you help @xseignard?

**Comment by xseignard** [comment]
Hello @citrusui 

Could you show me your `package.json` and your `electron-builder` config?

I guess your executable has the wrong name compared to the one created by `electron-packager`. 
It would be better to be able to derivate it from the `package.json` but for now, you should set it.

Regards

**Comment by citrusui** [comment]
`electron-builder` config:

```json
{
  "linux" : {
    "arch" : 64,
    "target" : "deb",
    "version" : "0.0.1",
    "title" : "Team Hours",
    "comment" : "View your team hours.",
    "executable" : "teamhours",
    "maintainer": "Avery Magnotti <averymagnotti@outlook.com>"
  }
}
```

`package.json`:

```json
{
  "name": "teamhours",
  "version": "0.0.1",
  "author": "Triple Helix",
  "contributors": {
    "name": "Avery Magnotti",
    "email": "averymagnotti@outlook.com"
  },
  "keywords": [
    "photon",
    "electron",
    "triple helix"
  ],
  "style": "css/bootstrap.min.css",
  "repository": {
    "type": "git",
    "url": "https://github.com/2363web/teamhours"
  },
  "bugs": {
    "url": "https://github.com/2363web/teamhours/issues"
  },
  "scripts": {
    "start": "electron .",
    "local": "http-server . -a localhost -o",
    "pkg:linux": "electron-packager . \"Team Hours\" --platform=linux --arch=x64 --version=0.36.7 --overwrite --asar=true --icon=icons/icon.png --out=dist --ignore=dist",
    "pkg:osx": "electron-packager . \"Team Hours\" --platform=darwin --arch=x64 --version=0.36.7 --overwrite --asar=true --icon=icons/icon.icns --out=dist --app-version=0.0.1 --build-version=0.0.1 --app-bundle-id=com.team2363.teamhours --helper-bundle-id=com.team2363.helper app-category-type=public.app-category.utilities --ignore=dist",
    "pkg:win": "electron-packager . \"Team Hours\" --platform=win32 --arch=x64 --version=0.36.7 --overwrite --asar=true --icon=icons/icon.ico --out=dist --version-string.CompanyName=\"Triple Helix\" --version-string.ProductName=\"Team Hours\" --version-string.FileDescription=\"Team Hours\" --version-string.LegalCopyright=\"Copyright (c) 2016 Triple Helix.\" --version-string.ProductVersion=0.1 --version-string.FileVersion=0.1 --version-string.InternalName=Pinout --version-string.OriginalFilename=\"Team Hours\" --ignore=dist"
  },
  "license": "MIT",
  "devDependencies": {
    "electron-packager": "^5.2.1",
    "electron-prebuilt": "^0.36.7",
    "http-server": "^0.8.5"
  }
}
```

**Comment by xseignard** [comment]
Ok, so the problem is that `electron-packager` produces an executable called after the `<appname>` you provide.

Here it is `Team Hours`, with a space, that mess up the `electron-builder` packaging (it's a bad practice to put a space in a linux executable anyway).

I tried with your repo and did the following changes in `package.json` scripts:
```
"pkg:linux": "electron-packager . teamhours --platform=linux --arch=x64 --version=0.36.7 --overwrite --asar=true --icon=icons/icon.png --out=dist --ignore=dist",
"builder:linux": "electron-builder dist/teamhours-linux-x64 --platform=linux --out=dist/ --config=config.json"
```

I left your `config.json` unchanged, and I could create the deb, and install it, and run it.

Regards

**Comment by citrusui** [comment]
Thanks! I'll try this when I get home from school. :+1:

**Comment by citrusui** [comment]
Whoops, it still doesn't work. Let me demonstrate:

![build linux](https://cloud.githubusercontent.com/assets/9056756/12897367/fc507f40-ce74-11e5-82a2-3fd9ea29d814.gif)

On another note...

Even though `appdmg` is optional (because OS X), it still tries to install itself when I `npm install`.

![screenshot from 2016-02-08 14 37 03](https://cloud.githubusercontent.com/assets/9056756/12896751/b5054e7a-ce71-11e5-9512-76e252fd00d5.png)

I do know how to resolve this manually, but it can become tedious if you ever need to download the dependencies on another platform (e.g. Windows).

Maybe it should be a separate issue? I don't know yet.

**Comment by stefanjudis** [comment]
I don't get that one...

> Even though appdmg is optional (because OS X), it still tries to install itself when I npm install.

The problem is not that tries to install but rather that it is executing `lib/osx.js`.... Honestly I have no clue how you got there... 

And I don't unterstand the gif in combination with the screenshot? the gif doesn't show the error... where is this screenshot then coming from?

**Comment by xseignard** [comment]
@stefanjudis actually, in `platforms.js` we should only require `osx.js` if we are on a mac, where `appdmg` is compatible.

**Comment by stefanjudis** [comment]
right... You correct... Thanks for pointing that out. :)

I created a ticket for it... 
I'll quickly tackle this one then https://github.com/loopline-systems/electron-builder/issues/130 and we'd be able to push out another `patch` version?

**Comment by stefanjudis** [comment]
@xseignard 

> actually, in platforms.js we should only require osx.js if we are on a mac, where appdmg is compatible.

Would be better to really only require the things we need, or? So only `win.js` when someone wants to build for windows, only `linux.js` when someone wants to build for linux, ...

**Comment by citrusui** [comment]
The screenshot is a separate issue; the appdmg dependency.

The GIF demonstrates me compiling a Debian package with `electron-builder` and showing how it still **doesn't work**. There is nothing in `usr/bin`.

**Comment by xseignard** [comment]
Have you tried to install it? There are some scripts that run after install that will create symlinks.

Do you have installed `fpm`?

**Comment by citrusui** [comment]
fpm is installed.

I did indeed install it, but it only created a .desktop config in `/usr/share/applications`.

**Comment by xseignard** [comment]
Did you try to install it?

**Comment by citrusui** [comment]
Yes, I installed the generated .deb package.

**Comment by xseignard** [comment]
Hello @citrusui 

I'm sorry but I cannot understand the issue. All you say is normal to me. Nothing in `usr/bin` in the deb is normal.

Executables are linked in a postinstall step, thanks to the following script: https://github.com/loopline-systems/electron-builder/blob/master/templates/linux/after-install.tpl

In your gif, the package seems to have the right shape.

Does the deb installation let you launch your app? Once installed, you could launch it in a terminal with `teamhours` ?

The `.desktop ` file in `usr/share/applications` in the deb should be enough to find your app in your linux menus, right?

**Comment by stefanjudis** [comment]
@citrusui the appdmg issue should be solved with version `v2.7.2`. :bowtie:

**Comment by citrusui** [comment]
@stefanjudis awesome.

However, I still can't launch `teamhours` through a terminal. I even thought to rename my app `team-hours` since the generated Debian package calls itself "team-hours"

**Comment by xseignard** [comment]
@citrusui could you please provide your deb?

**Comment by citrusui** [comment]
@xseignard here you go
[teamhours-0.0.1-amd64.zip](https://github.com/loopline-systems/electron-builder/files/123844/teamhours-0.0.1-amd64.zip)

**Comment by xseignard** [comment]
Ok, so the app is not packaged (e.g. not in `opts`)

Could you please provide your package.json?

**Comment by citrusui** [comment]
package.json:
```
{
  "name": "teamhours",
  "version": "0.0.1",
  "author": "Triple Helix",
  "contributors": {
    "name": "Avery Magnotti",
    "email": "averymagnotti@outlook.com"
  },
  "keywords": [
    "bootstrap",
    "electron",
    "triple helix"
  ],
  "style": "css/bootstrap.min.css",
  "repository": {
    "type": "git",
    "url": "https://github.com/2363web/teamhours"
  },
  "bugs": {
    "url": "https://github.com/2363web/teamhours/issues"
  },
  "scripts": {
    "start": "electron .",
    "local": "http-server . -a localhost -o",
    "build:linux": "electron-builder dist --platform=linux --out dist/ --config=config.json",
    "pkg:linux": "electron-packager . \"Team Hours\" --platform=linux --arch=x64 --version=0.36.7 --overwrite --asar=true --icon=icons/icon.png --out=dist --ignore=dist",
    "pkg:osx": "electron-packager . \"Team Hours\" --platform=darwin --arch=x64 --version=0.36.7 --overwrite --asar=true --icon=icons/icon.icns --out=dist --app-version=0.0.1 --build-version=0.0.1 --app-bundle-id=com.team2363.teamhours --helper-bundle-id=com.team2363.helper app-category-type=public.app-category.utilities --ignore=dist",
    "pkg:win": "electron-packager . \"Team Hours\" --platform=win32 --arch=x64 --version=0.36.7 --overwrite --asar=true --icon=icons/icon.ico --out=dist --version-string.CompanyName=\"Triple Helix\" --version-string.ProductName=\"Team Hours\" --version-string.FileDescription=\"Team Hours\" --version-string.LegalCopyright=\"Copyright (c) 2016 Triple Helix.\" --version-string.ProductVersion=0.1 --version-string.FileVersion=0.1 --version-string.InternalName=Pinout --version-string.OriginalFilename=\"Team Hours\" --ignore=dist"
  },
  "license": "MIT",
  "devDependencies": {
    "electron-builder": "^2.7.2",
    "electron-packager": "^5.2.1",
    "electron-prebuilt": "^0.36.7",
    "http-server": "^0.8.5"
  }
}
```

**Comment by stefanjudis** [comment]
@citrusui 

```
$ electron-builder dist/win/someFancy-linux-x64 --platform=linux --out=/some/path/ --config=config.json
```

You not pointing at the linux package aren't you?

**Comment by xseignard** [comment]
@stefanjudis true
@citrusui please double check my comment here: https://github.com/loopline-systems/electron-builder/issues/129#issuecomment-181373760

**Comment by citrusui** [comment]
I think I now realize why this wasn't working!

You have to run `electron-packager` before `electron-builder` in order to fetch the executable.

However, for whatever reason, my .desktop entry still points to /usr/bin/teamhours (when it should really be pointing to /usr/opt/teamhours/teamhours-linux-x64/teamhours

**Comment by stefanjudis** [comment]
> I think I now realize why this wasn't working!
> You have to run electron-packager before electron-builder in order to fetch the executable.

Can you maybe go over the readme and read it again... I though this was clear... :( Suggestions and/or a PR fixing this missunderstanding would be great.

**Comment by xseignard** [comment]
@citrusui this is normal as stated here https://github.com/loopline-systems/electron-builder/issues/129#issuecomment-181845526

Please change the following in your `package.json` and everything will be fine:

```
"build:linux": "electron-builder dist --platform=linux --out dist/ --config=config.json",
 "pkg:linux": "electron-packager . \"Team Hours\" --platform=linux --arch=x64 --version=0.36.7 --overwrite --asar=true --icon=icons/icon.png --out=dist --ignore=dist",
```

to

```
"build:linux": "electron-builder dist/teamhours-linux-x64 --platform=linux --out=dist/ --config=config.json"
"pkg:linux": "electron-packager . teamhours --platform=linux --arch=x64 --version=0.36.7 --overwrite --asar=true --icon=icons/icon.png --out=dist --ignore=dist",
```

**Comment by citrusui** [comment]
okay! Finally working (for real). There's a minor issue to discuss but I'll open a new issue for that.

**Comment by stefanjudis** [comment]
@citrisui As said it'd be great if you could give hints why things we're not clear. :blush:
